var x=7;
+console.log("suma de numeros :");
+x++;
+console.log("7+1="+x);
+x++;
+console.log("7+2="+x);
+x++;
+console.log("7+3="+x);
+x++;
+console.log("7+4="+x);
+x++;
+console.log("7+5="+x);
+x++;
+console.log("7+6="+x);
+x++;
+console.log("7+7="+x);
+x++;
+console.log("7+8="+x);
+x++;
+console.log("7+9="+x);
+x++;
+console.log("7+10="+x);